function(cgen_target_private_emscripten_options TARGETNAME)
  list(REMOVE_AT ARGV 0)
  target_compile_options(${TARGETNAME} PRIVATE ${ARGV})
  target_link_options(${TARGETNAME} PRIVATE ${ARGV})
endfunction(cgen_target_private_emscripten_options)

function(cgen_embuild TARGETNAME)
  list(REMOVE_AT ARGV 0)
  set(CURRENT_TYPE "")
  set(COMMONFLAGS "")
  set(DEBFLAGS "")
  set(RELFLAGS "")

  foreach(arg ${ARGV})
    if(arg MATCHES "COMMONFLAGS")
      set(CURRENT_TYPE "COMMONFLAGS")
    elseif(arg MATCHES "DEBFLAGS")
      set(CURRENT_TYPE "DEBFLAGS")
    elseif(arg MATCHES "RELFLAGS")
      set(CURRENT_TYPE "RELFLAGS")
    else()
      list(APPEND ${CURRENT_TYPE} ${arg})
    endif()
  endforeach()

  list(LENGTH COMMONFLAGS CFLEN)
  if(NOT ${CFLEN} MATCHES 0)
    cgen_target_private_emscripten_options(${TARGETNAME} ${COMMONFLAGS})
  endif()

  if(${CMAKE_BUILD_TYPE} MATCHES "Debug")
    list(LENGTH DEBFLAGS DBLEN)
    if(NOT ${DBLEN} MATCHES 0)
      cgen_target_private_emscripten_options(${TARGETNAME} ${DEBFLAGS})
    endif()
  else()
    list(LENGTH RELFLAGS RLLEN)
    if(NOT ${RLLEN} MATCHES 0)
      cgen_target_private_emscripten_options(${TARGETNAME} ${RELFLAGS})
    endif()
  endif()
endfunction(cgen_embuild)
