function (cgen_target_vcrt_mt target enabled)
if(MSVC)
  if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.15.0")
    if(enabled)
      set_target_properties(${target} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    else()
      set_target_properties(${target} PROPERTIES MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    endif()
  else()
    if(enabled)
      target_compile_options(${target} PRIVATE "/MT$<$<CONFIG:Debug>:d>")
    else()
      target_compile_options(${target} PRIVATE "/MD$<$<CONFIG:Debug>:d>")
    endif()
  endif()
endif(MSVC)
endfunction()
